version: '3.8'

services:
  db:
    container_name: pgsqldb
    image: pgvector/pgvector:pg16 # ankane/pgvector:latest
    restart: unless-stopped
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: dowado
      POSTGRES_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - "6024:5432"
    networks:
      - default

volumes:
  pgvector_data:


networks:
  default:
    driver: bridge
    name: dowado
